---
- hosts: webservers 
  become: yes
  tasks:
    - name: Install packages
      apt:
        name: "httpd"
        state: "present"
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
...
